# /etc/nginx/snippets/custom-50x.conf

error_page 500 502 503 504 /50x.html;

location = /50x.html {
   internal;
   root /var/www/nginx-errors;
   add_header Content-Security-Policy 
      "default-src 'none'; 
      base-uri 'none'; 
      form-action 'none'; 
      frame-ancestors 'none'; 
      object-src 'none'" always;
}
